### ISSUE TITLE
Internal Server Error: /solr/data_set_manager/select/

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#705] opened 2015-09-21 21:34 UTC
Dozens of tracebacks logged over the past couple of weeks. HTTPError exception should be handled on the server side.

```
Traceback (most recent call last):

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/srv/scc/apps/refinery-platform/refinery/core/views.py", line 557, in solr_select
    f = urllib2.urlopen(req)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)

  File "/n/sw/centos6/python-2.7.3/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

HTTPError: HTTP Error 400: Bad Request


<WSGIRequest
path:/solr/data_set_manager/select/,
GET:<QueryDict: {u'sort': [u'Replicate_Id_Comment_1556_787_s asc'], u'fq': [u'(study_uuid:393f8727-ae24-4744-abc9-20fd99d5124f AND assay_uuid:6b22580a-d1c0-4309-bc7d-ea52eb28cf68)', u'type:("Raw Data File" OR "Derived Data File" OR "Array Data File" OR "Derived Array Data File" OR "Array Data Matrix File" OR "Derived Array Data Matrix File")', u'is_annotation:false'], u'rows': [u'20'], u'facet.field': [u'REFINERY_ANALYSIS_UUID_1556_787_s', u'REFINERY_WORKFLOW_OUTPUT_1556_787_s', u'REFINERY_SUBANALYSIS_1556_787_s'], u'facet.limit': [u'-1'], u'facet.sort': [u'count'], u'facet': [u'true'], u'json.wrf': [u'jQuery21109138111628126353_1442870835444'], u'q': [u'django_ct:data_set_manager.node'], u'start': [u'0'], u'wt': [u'json'], u'facet.pivot': [u','], u'fl': [u'Replicate_Id_Comment_1556_787_s,file_uuid,name,REFINERY_TYPE_1556_787_s,organism_Characteristics_1556_787_s,REFINERY_ANALYSIS_UUID_1556_787_s,notes_Characteristics_1556_787_s,type,study_uuid,cell_type_Characteristics_1556_
787_s,genotype_Characteristics_1556_787_s,Group_Name_Comment_1556_787_s,REFINERY_FILETYPE_1556_787_s,REFINERY_NAME_1556_787_s,uuid,strain_Characteristics_1556_787_s,assay_uuid,REFINERY_WORKFLOW_OUTPUT_1556_787_s,is_annotation,REFINERY_SUBANALYSIS_1556_787_s'], u'_': [u'1442870835447']}>,
POST:<QueryDict: {}>,
COOKIES:{'__utma': '165092284.386764576.1442870722.1442870722.1442870722.1',
'__utmb': '165092284.0.10.1442870722',
'__utmc': '165092284',
'__utmz': '165092284.1442870722.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)',
'csrftoken': 'CrNwgBU22KU5tVJvoVPD1VlAN55MVku7',
'messages': '47da36c5bfc3a265a233602e1cb3c8f68d8e3cd2$[["__json_message",0,25,"If you don\'t want to fill your profile out now, you can go to the <a href=\'/\'>homepage</a>.","safe"]]',
'sessionid': '0jkobi7s3cmiy9gy3rj5vclcjx361l93'},
META:{u'CSRF_COOKIE': u'CrNwgBU22KU5tVJvoVPD1VlAN55MVku7',
'DJANGO_SETTINGS_MODULE': 'config.settings.prod',
'DOCUMENT_ROOT': '/var/www/html',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'sessionid=0jkobi7s3cmiy9gy3rj5vclcjx361l93; messages="47da36c5bfc3a265a233602e1cb3c8f68d8e3cd2$[[\\"__json_message\\"\\0540\\05425\\054\\"If you don\'t want to fill your profile out now\\054 you can go to the <a href=\'/\'>homepage</a>.\\"\\054\\"safe\\"]]"; __utma=165092284.386764576.1442870722.1442870722.1442870722.1; __utmb=165092284.0.10.1442870722; __utmc=165092284; __utmz=165092284.1442870722.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); csrftoken=CrNwgBU22KU5tVJvoVPD1VlAN55MVku7',
'HTTP_DNT': '1',
'HTTP_HOST': 'refinery-dev.stemcellcommons.org',
'HTTP_REFERER': 'https://refinery-dev.stemcellcommons.org/data_sets/fe9edc18-ae83-4956-b6a5-76cd3ba4f704/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36',
'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
'PATH_INFO': u'/solr/data_set_manager/select/',
'PATH_TRANSLATED': '/srv/scc/apps/refinery-platform/refinery/config/wsgi.py/solr/data_set_manager/select/',
'QUERY_STRING': 'q=django_ct:data_set_manager.node&wt=json&json.wrf=jQuery21109138111628126353_1442870835444&start=0&rows=20&fq=(study_uuid:393f8727-ae24-4744-abc9-20fd99d5124f%20AND%20assay_uuid:6b22580a-d1c0-4309-bc7d-ea52eb28cf68)&fq=type:(%22Raw%20Data%20File%22%20OR%20%22Derived%20Data%20File%22%20OR%20%22Array%20Data%20File%22%20OR%20%22Derived%20Array%20Data%20File%22%20OR%20%22Array%20Data%20Matrix%20File%22%20OR%20%22Derived%20Array%20Data%20Matrix%20File%22)&fq=is_annotation:false&facet.field=REFINERY_ANALYSIS_UUID_1556_787_s&facet.field=REFINERY_WORKFLOW_OUTPUT_1556_787_s&facet.field=REFINERY_SUBANALYSIS_1556_787_s&facet.sort=count&facet.limit=-1&facet=true&fl=Replicate_Id_Comment_1556_787_s,file_uuid,name,REFINERY_TYPE_1556_787_s,organism_Characteristics_1556_787_s,REFINERY_ANALYSIS_UUID_1556_787_s,notes_Characteristics_1556_787_s,type,study_uuid,cell_type_Characteristics_1556_787_s,genotype_Characteristics_1556_787_s,Group_Name_Comment_1556_787_s,REFINERY_FILETY
PE_1556_787_s,REFINERY_NAME_1556_787_s,uuid,strain_Characteristics_1556_787_s,assay_uuid,REFINERY_WORKFLOW_OUTPUT_1556_787_s,is_annotation,REFINERY_SUBANALYSIS_1556_787_s&sort=Replicate_Id_Comment_1556_787_s%20asc&facet.pivot=,&_=1442870835447',
'REMOTE_ADDR': '134.174.140.208',
'REMOTE_PORT': '3138',
'REQUEST_METHOD': 'GET',
'REQUEST_URI': '/solr/data_set_manager/select/?q=django_ct:data_set_manager.node&wt=json&json.wrf=jQuery21109138111628126353_1442870835444&start=0&rows=20&fq=(study_uuid:393f8727-ae24-4744-abc9-20fd99d5124f%20AND%20assay_uuid:6b22580a-d1c0-4309-bc7d-ea52eb28cf68)&fq=type:(%22Raw%20Data%20File%22%20OR%20%22Derived%20Data%20File%22%20OR%20%22Array%20Data%20File%22%20OR%20%22Derived%20Array%20Data%20File%22%20OR%20%22Array%20Data%20Matrix%20File%22%20OR%20%22Derived%20Array%20Data%20Matrix%20File%22)&fq=is_annotation:false&facet.field=REFINERY_ANALYSIS_UUID_1556_787_s&facet.field=REFINERY_WORKFLOW_OUTPUT_1556_787_s&facet.field=REFINERY_SUBANALYSIS_1556_787_s&facet.sort=count&facet.limit=-1&facet=true&fl=Replicate_Id_Comment_1556_787_s,file_uuid,name,REFINERY_TYPE_1556_787_s,organism_Characteristics_1556_787_s,REFINERY_ANALYSIS_UUID_1556_787_s,notes_Characteristics_1556_787_s,type,study_uuid,cell_type_Characteristics_1556_787_s,genotype_Characteristics_1556_787_s,Group_Name_Comm
ent_1556_787_s,REFINERY_FILETYPE_1556_787_s,REFINERY_NAME_1556_787_s,uuid,strain_Characteristics_1556_787_s,assay_uuid,REFINERY_WORKFLOW_OUTPUT_1556_787_s,is_annotation,REFINERY_SUBANALYSIS_1556_787_s&sort=Replicate_Id_Comment_1556_787_s%20asc&facet.pivot=,&_=1442870835447',
'SCRIPT_FILENAME': '/srv/scc/apps/refinery-platform/refinery/config/wsgi.py',
'SCRIPT_NAME': u'',
'SERVER_ADDR': '10.242.110.105',
'SERVER_ADMIN': 'root@localhost',
'SERVER_NAME': 'refinery-dev.stemcellcommons.org',
'SERVER_PORT': '443',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '<address>Apache/2.2.15 (CentOS) Server at refinery-dev.stemcellcommons.org Port 443</address>\n',
'SERVER_SOFTWARE': 'Apache/2.2.15 (CentOS)',
'SSL_TLS_SNI': 'refinery-dev.stemcellcommons.org',
'apache.version': (2, 2, 15),
'mod_wsgi.application_group': 'refinery-dev.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.daemon_connects': '1',
'mod_wsgi.daemon_restarts': '0',
'mod_wsgi.daemon_start': '1442870836973724',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '443',
'mod_wsgi.process_group': 'scc',
'mod_wsgi.queue_start': '1442870836973599',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.request_start': '1442870836973333',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.script_start': '1442870836974849',
'mod_wsgi.version': (4, 3, 1),
'wsgi.errors': <mod_wsgi.Log object at 0x7f91d54d9468>,
'wsgi.file_wrapper': <type 'mod_wsgi.FileWrapper'>,
'wsgi.input': <mod_wsgi.Input object at 0x7f91d72087b0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'https',
'wsgi.version': (1, 0)}>
```

**Comment by ngehlenborg** [comment] 2015-09-22 14:49
Related to #670?

**Comment by ngehlenborg** [comment] 2015-09-29 18:34
Closing as duplicate of #670.

**Closed by ngehlenborg** 2015-09-29 18:34 UTC
Labels: bug, server, solr, technical debt
