### ISSUE TITLE
Firefox: Dataset "preview" URLs do not load preview

### ISSUE THREAD

**Issue by mccalluc** [parklab/refinery-platform#1312] opened 2016-08-08 20:04 UTC
Commit: 33de42c5dcd1e22fe17e4

### Steps to reproduce
- **Only on Firefox**
- From the Launch Pad, click on any one of the available data sets.
- It expands to the right, and the URL updates to "/#/preview/..."
- Reload
- or click on another data set

### Observed behavior
the preview pane is just empty.

### Expected behavior
The preview should be rendered.

<img width="628" alt="screen shot 2016-08-08 at 4 02 39 pm" src="https://cloud.githubusercontent.com/assets/730388/17494184/9df5fb68-5d81-11e6-83c3-c9b8b8702971.png">

**Comment by hackdna** [comment] 2016-09-21 21:35
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2q6R8R6c&#x2F;315-fix-data-set-browsing-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> fix data set browsing bugs</a>

**Comment by flekschas** [comment] 2016-09-29 20:30
Can't reproduce with FF 49 when clicking on multiple data sets one after the other.
Can reproduce the reload issue.

Might be loading hiccup.

(Tested in demo.stemcellcommons.org)

**Comment by jkmarx** [comment] 2016-09-29 20:37
48.0.2
![sep-29-2016 16-36-50](https://cloud.githubusercontent.com/assets/9956764/18971405/f1b958a8-8662-11e6-9ff9-a56a8e875a52.gif)

**Comment by jkmarx** [comment] 2016-09-29 20:38
49.0.1 , locally I'm still having the same issue

**Comment by jkmarx** [comment] 2016-09-29 20:39
Same issue on the beta site. https://beta.stemcellcommons.org

**Comment by ngehlenborg** [comment] 2016-09-30 13:17
I am also still having the issue with Firefox 49.0.1. But to me this is a fairly low priority issues since users will rarely run into it and if they do, the workaround is simple.

**Comment by flekschas** [comment] 2016-09-30 14:22
This issue relates to how Chrome and FF load the Angular app. One of the controller is not yet initialized at the time the preview panel is opened. This simply causes a styling issue. Basically the preview is loaded etc. but you can't see it because a CSS property hasn't been updated yet. I thought $timeout(..., 0) ensures that at least everything has been initialized but that doesn't seem to be the case in every browser.

**Comment by flekschas** [comment] 2016-09-30 15:35
Fixed in https://github.com/parklab/refinery-platform/tree/flekschas/fix-preview-ff. Please merge when you're ready.

**Comment by hackdna** [comment] 2016-09-30 15:45
Great, thanks. Could you submit a pull request?

**Comment by flekschas** [comment] 2016-09-30 16:48
Running into a weird issue with a unit test that is suddenly failing locally (the related source code didn't change) and Travis is failing for some other reason (not finding some selenium executable). As soon as at least Travis is running through I'll create the pull request.

**Closed** 2016-10-04 17:52 UTC
Labels: bug, ui
