### ISSUE TITLE
Uploading files through the data file uploader causes high CPU usage

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#549] opened 2015-06-30 20:08 UTC
Steps to reproduce:
1. Going to http://192.168.50.50:8000/data_set_manager/import/ and choosing the _data_ tab
2. Choose a picture from your computer
3. Hit Start on the individual file

The CPU usage for this Chrome tab goes up to 30-40% and stays there, even though the console outputs.

```Finished uploading chunks for: Bildschirmfoto 2015-06-29 um 17.45.37.PNG md5 = 8cf7483ce2074f8fa9e3b0ded496fb23
data_file_upload.js:147 Object {message: "You successfully uploaded this file"}```

**Comment by hackdna** [comment] 2015-07-21 18:29
About 10% in Safari and about 25-30% in Firefox.

**Comment by ngehlenborg** [comment] 2015-07-23 13:09
Unclear what is causing this but it seems to be either an issue with the library or the underlying browser APIs. Moving to [0.0.5](https://github.com/parklab/refinery-platform/milestones/Release%200.0.5).

**Comment by flekschas** [comment] 2015-09-01 15:47
It's most likely not a library issue. I assessed the performance with Firefox's dev tools and even though Firefox uses 33% of my CPU. The performance profiler does only show CSS redraw events. Not a single piece of JS is called after a short initial time frame.

**Comment by hackdna** [comment] 2015-09-01 15:59
Thanks, so it's some sort of CSS rendering bug?

**Comment by ngehlenborg** [comment] 2015-09-01 16:02
@hackdna: which browser API is this built upon?

**Comment by flekschas** [comment] 2015-09-01 16:06
Maybe it is maybe its's not. The dashboard also causes some CSS related rendering but doesn't nearly use 33% of my CPU. FileAPI I suppose but if this would be a FileAPI issue others would probably have reported it. Testing some example implementation of `ng-file-upload` doesn't cause any trouble with the CPU.

**Comment by hackdna** [comment] 2015-09-01 16:06
(File API)[https://developer.mozilla.org/en-US/docs/Web/API/File]. The source code for the library is here: https://github.com/blueimp/jQuery-File-Upload

**Comment by flekschas** [comment] 2015-09-01 16:11
Okay its not the CSS rendering... I totally forgot about the constantly spinning cog-wheel.

**Comment by ngehlenborg** [comment] 2015-09-01 16:14
I just reproduced the issue with this demo implementation of the library: https://blueimp.github.io/jQuery-File-Upload/angularjs.html

Can someone confirm? If so, we can close this. It seems to be an issue of this library in the context of Angular. After uploading the CPU load of the tab remains at around 17%.

![screen shot 2015-09-01 at 12 14 02 pm](https://cloud.githubusercontent.com/assets/1216518/9609688/03193dee-50a3-11e5-877d-9737a75c6032.png)

**Comment by flekschas** [comment] 2015-09-01 16:19
I can confirm this.

**Comment by hackdna** [comment] 2015-09-01 16:21
Same here: 13-16% for the jQuery file upload tab and for the GPU process. It stops when the tab is not in the foreground.

**Comment by ngehlenborg** [comment] 2015-09-01 16:27
Navigating away from the import page after upload brings the load back to < 5%. 

I am tempted to close this but it seems that there is some additive effect: when I add 90 or so files at once, the CPU load stays at > 60%. 

@flekschas: could you do a quick check for common Angular performance issues?

**Comment by flekschas** [comment] 2015-09-01 16:31
It's not a visual issue, CPU stays high even when I disable CSS styling.

ngStats doesn't show anything and the CPU profiler says that no JS runs after clicking the upload finished.

**Comment by ngehlenborg** [comment] 2015-09-01 16:38
I am closing this. I don't see how we can address it and since the load goes back down after navigating away from the page it is not a real issue.

**Closed by ngehlenborg** 2015-09-01 16:38 UTC
Labels: bug, import

**Comment by flekschas** [comment] 2015-09-01 17:34
I've opened a stackoverflow question. lets see if anybody ran into that issue as well https://stackoverflow.com/questions/32336894/jquery-file-upload-with-angularjs-causes-high-cpu-usage

**Comment by hackdna** [comment] 2016-11-16 02:17
![](https://github.trello.services/images/mini-trello-icon.png) [Reduce high CPU usage in data file upload view after uploading completes](https://trello.com/c/jwPw2oGM/80-reduce-high-cpu-usage-in-data-file-upload-view-after-uploading-completes)
