### ISSUE TITLE
500 Error from Analysis API 

### ISSUE THREAD

**Issue by jkmarx** [parklab/refinery-platform#761] opened 2015-10-27 14:58 UTC
### Reproduce
1) Locally, LOG OUT. 
2) Select a public dataset which has analyses.
3) Go to the dataset view.

### Observed
<img width="1426" alt="screen shot 2015-10-27 at 10 52 49 am" src="https://cloud.githubusercontent.com/assets/9956764/10761823/83afff66-7c99-11e5-9ab6-9caa30945ddf.png">

### Expected
No errors.

**Comment by jkmarx** [comment] 2015-10-27 15:00
Similar to #714 certain API calls should not be made unless the user has dataset permission and/or logged in.

**Comment by scottx611x** [comment] 2015-11-02 15:35
Related to  #764

**Comment by hackdna** [comment] 2015-11-02 15:37
API should be robust enough to handle any calls without crashing.

**Comment by scottx611x** [comment] 2015-11-02 15:38
**Stemming from the same issue:**
***
**Reproduce:**
Hit endpoint: `api/v1/analysis/` as `AnonymousUser`

**Observed:**
```
Traceback (most recent call last):

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 440, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 472, in dispatch
    response = method(request, **kwargs)

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 1285, in get_list
    bundles.append(self.full_dehydrate(bundle))

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 854, in full_dehydrate
    bundle = self.dehydrate(bundle)

  File "/srv/scc/apps/refinery-platform/refinery/core/api.py", line 669, in dehydrate
    if bundle.request.user.userprofile.uuid == bundle.data['owner']:

  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/functional.py", line 205, in inner
    return func(self._wrapped, *args)

AttributeError: 'AnonymousUser' object has no attribute 'userprofile’
```

**Expected:**
No 500 Error

**Comment by ngehlenborg** [comment] 2015-12-08 15:04
@scottx611x: Has this been addressed?

**Comment by scottx611x** [comment] 2015-12-09 21:41
I am not able to reproduce this error anymore. @jkmarx could you please try this out as well?

**Comment by jkmarx** [comment] 2015-12-09 21:53
I cannot reproduce this error, locally.

**Comment by scottx611x** [comment] 2015-12-09 21:54
Closing as this issue does not occur anymore

**Closed by scottx611x** 2015-12-09 21:54 UTC
Labels: analysis, bug, ui
