### ISSUE TITLE
Unable to launch IGV for RNA-seq's tophat_accepted_hits file (bam format)

### ISSUE THREAD

**Issue by sjhosui** [parklab/refinery-platform#1251] opened 2016-07-15 20:09 UTC
### Steps to reproduce
1. Load study in data browser: https://test.stemcellcommons.org/data_sets/6ded23f9-3259-4449-b0ba-d27ef47101b3/#/files/browse

2. Select one of the "tophat_accepted_hits" files

3. Click on the visualize tab

4. Select "Current Selection"

### Observed behavior
Sorry! Unable to configure IGV for the selected file set.

### Expected behavior
Select genome build (?) and launch IGV

**Comment by hackdna** [comment] 2016-07-19 15:21
The workflows are in https://github.com/stemcellcommons/scc-galaxy-tools/tree/master/rnaseq_workflows.

**Comment by scottx611x** [comment] 2016-07-22 14:08
@sjhosui @hackdna I am not able to reproduce this error. (the DS referenced in the issue doesn't seem to exist anymore) 

Regardless, this error message does not pop up while vizualizing other `tophat_accepted_hits` bams

Also, It looks like that code on the test site was updated recently so maybe something got fixed by chance??

**Comment by hackdna** [comment] 2016-07-22 19:11
I've just tried this on https://test.stemcellcommons.org/data_sets/9a90076a-f795-4af1-86a4-fbd45630f314/#/files/visualize/ and I didn't get the error described but I am getting this error message from IGV:
`Errors were encountered loading the session: http://test.stemcellcommons.org/media/file_store/15/d4/1_tophat_accepted_hits.bam &nbs;p org.broad.igv.exceptions.DataLoadException: An error occurred while accessing: http://test.stemcellcommons.org/media/file_store/15/d4/1_tophat_accepted_hits.bai Index file not found. Tried http://test.stemcellcommons.org/media/file_store/15/d4/1_tophat_accepted_hits.bai `
Commit: 29745d057ba2ee5e4da65c05e74f3ee31915be1d

**Comment by hackdna** [comment] 2016-07-22 20:07
Opened a new issue #1264.

**Closed by hackdna** 2016-07-22 20:07 UTC
Labels: bug, visualization

**Comment by hackdna** [comment] 2016-10-18 20:42
![](https://github.trello.services/images/mini-trello-icon.png) [IGV cannot visualize BAM files produced by RNA-seq workflows](https://trello.com/c/mL01SbVo/325-igv-cannot-visualize-bam-files-produced-by-rna-seq-workflows)
