### ISSUE TITLE
javascript spark-md5 error in firefox

### ISSUE THREAD

**Issue by fjrmoreews** [parklab/refinery-platform#1222] opened 2016-07-06 15:19 UTC
Hi, on my instance,  I have a js error in the upload page related to the md5 local computation.
Regards,
FJR  Moreews

### Steps to reproduce
1.OS  :ubuntu 14.04, browser : firefox 43.0.4 

http://[...]/data_set_manager/import/#/upload/
"add files..." button  , "start upload" button

### Observed behavior
"Calculating MD5 " status image 
flash never stop

### Expected behavior
upload with green bar 

##issue : 
it's a javascript issue in firefox. It works fine in chrome.

### log (firefox)
"**ReferenceError: FileReader is not defined**"

GET 
[...] static/vendor/spark-md5/spark-md5.min.js [HTTP/1.1 200 OK 0ms]

function a(a){function c(){h.onload=function(b){f.append(b.target.result),g++,g<e?c():postMessage({name:a.name,md5:f.end()})},h.onerror=function(b){postMessage({name:a.name,error:b.message})};var i=g*b,j=Math.min(i+b,a.size);h.readAsArrayBuffer(d.call(a,i,j))}var d=File.prototype.slice||File.prototype.mozSlice||File.prototype.webkitSlice,e=Math.ceil(a.size/b),f=new self.SparkMD5.ArrayBuffer,g=0,h= new FileReader;
c()}var b=2097152;onmessage=function(c){importScripts(c.data[0]+"/static/vendor/spark-md5/spark-md5.min.js"),b=c.data[2],a(c.data[1])}

**Comment by fjrmoreews** [comment] 2016-07-06 15:43
additional remarks : I have no js error with the   test page 
 http://9px.ir/demo/incremental-md5.html
regards,
FJR

**Comment by scottx611x** [comment] 2016-07-12 15:41
I could reproduce this error with Firefox `38.0.5`.

Going to update to the latest and see if the issue persists.

**Comment by jkmarx** [comment] 2016-07-12 15:53
@scottx611x Thanks, I could not reproduce it with Firefox 47.0.1

**Comment by scottx611x** [comment] 2016-07-12 15:57
@fjrmoreews: Closing this as I could also not reproduce the issue in 47.0.1

![screen shot 2016-07-12 at 11 55 54 am](https://cloud.githubusercontent.com/assets/5629547/16773898/af36fb08-4827-11e6-90ea-ac14d6147cc0.png)

**Comment by jkmarx** [comment] 2016-07-12 15:58
@fjrmoreews Will you please upgrade your firefox browser and let us know if it resolves the issue? Thanks.

**Comment by jkmarx** [comment] 2016-07-20 15:23
Closing issue, since it has been over a week with no response.

**Comment by ngehlenborg** [comment] 2016-08-01 14:40
Likely related to #1282.

**Comment by hackdna** [comment] 2016-08-02 15:54
I was unable to upload files using Firefox 45 and Chrome 49 in Linux.

**Comment by jkmarx** [comment] 2016-08-02 16:58
@hackdna Can you reproduce the errors with the latest version of Firefox 47 and Chrome 51?

**Comment by hackdna** [comment] 2016-08-02 17:01
I'm testing in OS X now. Could you bring up a Linux VirtualBox and test there with those browsers/versions?

**Comment by ngehlenborg** [comment] 2016-08-09 14:04
We were unable to reproduce this with the latest version of Firefox (48) on OS X.

**Closed by ngehlenborg** 2016-08-09 14:04 UTC
Labels: bug, client, critical, files, import, ui
