### ISSUE TITLE
The number of data files returned by the API is incorrect.

### ISSUE THREAD

**Issue by flekschas** [parklab/refinery-platform#1013] opened 2016-04-15 15:51 UTC
Commit: e91867d903876ef61bdc9ce7a2c9572d3f5a7d7c

### Steps to reproduce
1. Go to http://192.168.50.50:8000
2. Open the data set summary panel for a data sets with derived files from an analysis.

### Observed behavior
Number of files doesn't increase.

### Expected behavior
Number of files should increase as newly derived files get added to the data set.

The displayed number of files is derived from the field _file_count_ of http://192.168.50.50:8000/api/v1/data_sets/9fc9bb6c-f885-4d1b-bcea-162f85285b0d/?format=json for example.

**Comment by jkmarx** [comment] 2016-05-02 12:26
@flekschas @ngehlenborg Is this a duplicate issue? #309

**Comment by ngehlenborg** [comment] 2016-05-02 12:35
Not a duplicate of but related to #309. This issue is about the number of file per data set and #309 is about the total size of all files in a data set.

**Comment by flekschas** [comment] 2016-05-02 16:04
It seems like `file_count` and `file_size` are not updated after an analysis ran. The methods `get_file_count` and `get_file_size` return the correct values.

**Comment by ngehlenborg** [comment] 2016-05-02 16:20
Can you try to updates those, @flekschas?

**Comment by flekschas** [comment] 2016-05-02 16:59
Yes I am on it.

**Comment by hackdna** [comment] 2016-05-06 16:53
Reopening due to #1094

**Closed** 2016-05-10 14:51 UTC
Labels: api, bug, dataset
