### ISSUE TITLE
Failing analyses

### ISSUE THREAD

**Issue by scottx611x** [parklab/refinery-platform#788] opened 2015-11-30 15:03 UTC
**Reproduce:**
Run an analysis with most recent code: 3b58608202c587a4e01059e642fbb106b15437cd

**Observed:**
All analyses fail w/ error: `Analysis execution failed: error importing analysis '%s' into Galaxy: %s`
![screen shot 2015-11-30 at 9 57 38 am](https://cloud.githubusercontent.com/assets/5629547/11474969/e3121204-9748-11e5-8191-9b966b9964b6.png)

**Expected:**
To be able to run analyses

**Comment by jkmarx** [comment] 2015-11-30 15:11
So, 8f239d55f23ce2365ca648eab4f5d669b64ffc6b was the last commit where I'm pretty sure analyses were running successfully. This was the last pull I made into the bootstrap3 branch and I checked the analyses were running.

**Comment by hackdna** [comment] 2015-11-30 16:30
Duplicate of #780?

**Comment by jkmarx** [comment] 2015-11-30 16:33
Yes, I believe so. Closed because it's a duplicate issue.

**Comment by scottx611x** [comment] 2015-11-30 16:33
@hackdna Yes, potentially. I am receiving a different error for my failing analyses than what is occurring in #780

**Closed** 2015-11-30 21:30 UTC
Labels: analysis, bug, critical, galaxy, server
