### ISSUE TITLE
ISA archive is imported even if it has been imported previously

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#562] opened 2015-07-15 21:57 UTC
## Steps to reproduce
Run process_isatab management command several times.  For example: `manage.py process_isatab admin ~/sccdata/51-100`

## Observed results
Command output on the first run:
`49 / 50: Successfully parsed isa_9505_764988.zip into DataSet with UUID 214ca952-4484-4b09-83e6-d98e0e8c5445`
Command output on subsequent runs:
`49 / 50: Successfully parsed isa_9505_764988.zip into DataSet with UUID 214ca952-4484-4b09-83e6-d98e0e8c5445`

## Expected results
Command output on the first run:
`49 / 50: Successfully parsed isa_9505_764988.zip into DataSet with UUID 214ca952-4484-4b09-83e6-d98e0e8c5445`
Command output on subsequent runs should indicate that the file is being skipped as it has been successfully parsed already.

**Comment by flekschas** [comment] 2015-07-15 23:50
The problem is caused by a trailing white space in the study title. (Thanks lord for trailing white spaces!) The Isatab-parsers's MD5 checker removed trailing white spaces but the normal `create_dataset` method doesn't. Thus when re-importing no existing data set is found.

**Comment by ngehlenborg** [comment] 2015-07-16 13:26
Any thoughts on what (remove whitespace or not) would be the better approach here?

**Comment by flekschas** [comment] 2015-07-16 13:37
Removing. Unless we want to have data sets named like ` name with hidden white spaces        `, which would be a different data set (from Django's point of view) than ` name with hidden white spaces       `.

**Comment by hackdna** [comment] 2015-07-16 13:43
Thanks for fixing the problem so quickly. Since this piece of code is used in two different places, it should be abstracted out into a separate method.

**Comment by flekschas** [comment] 2015-07-16 13:56
Please open a new issue for refactoring since this bug had been solved.

**Comment by hackdna** [comment] 2015-07-16 17:48
Still occurs with on f6186fe with the following ISA archives:
```
19 / 50: Successfully parsed isa_15576_819296.zip into DataSet with UUID 6a367997-20a4-4ed0-bbdd-deedaa9f4c61
20 / 50: Successfully parsed isa_15576_893881.zip into DataSet with UUID 6a367997-20a4-4ed0-bbdd-deedaa9f4c61
11 / 50: Successfully parsed isa_13880_668580.zip into DataSet with UUID dff6d61c-98ff-426b-a9af-4d777ea35965
12 / 50: Successfully parsed isa_14909_619781.zip into DataSet with UUID 9eee955f-4876-4178-a033-85596ae3913a
13 / 50: Successfully parsed isa_14910_796054.zip into DataSet with UUID ebf50342-89e6-4487-b008-da7afc314f66
16 / 50: Successfully parsed isa_14995_521844.zip into DataSet with UUID 9de08b61-7d11-4293-90f5-a69b0f7548a1
17 / 50: Successfully parsed isa_14995_760247.zip into DataSet with UUID 9de08b61-7d11-4293-90f5-a69b0f7548a1
19 / 50: Successfully parsed isa_15576_819296.zip into DataSet with UUID 6a367997-20a4-4ed0-bbdd-deedaa9f4c61
20 / 50: Successfully parsed isa_15576_893881.zip into DataSet with UUID 6a367997-20a4-4ed0-bbdd-deedaa9f4c61
25 / 50: Successfully parsed isa_15800_671535.zip into DataSet with UUID 33bc5088-d5fc-4d0c-8b83-44e7b86afc5e
26 / 50: Successfully parsed isa_15800_834651.zip into DataSet with UUID 33bc5088-d5fc-4d0c-8b83-44e7b86afc5e
39 / 50: Successfully parsed isa_16061_600320.zip into DataSet with UUID 3ac93890-89cb-42c4-ba19-e500ff79e8ef
40 / 50: Successfully parsed isa_16061_917105.zip into DataSet with UUID 3ac93890-89cb-42c4-ba19-e500ff79e8ef
41 / 50: Successfully parsed isa_16100_572948.zip into DataSet with UUID 0a2e6f93-a2af-4022-93aa-b23bfacc2076
42 / 50: Successfully parsed isa_16100_853304.zip into DataSet with UUID 0a2e6f93-a2af-4022-93aa-b23bfacc2076
49 / 50: Successfully parsed isa_15416_821364.zip into DataSet with UUID 0de958b1-10f0-45ac-8cd0-1a53ec7d7e69
50 / 50: Successfully parsed isa_15416_638201.zip into DataSet with UUID 0de958b1-10f0-45ac-8cd0-1a53ec7d7e69
```

**Comment by flekschas** [comment] 2015-07-16 19:00
Works fine for me. For example for isa_15576_819296.zip

```
(refinery-platform)vagrant@refinery:/vagrant/refinery$ ./manage.py process_isatab fritz /vagrant/transfer/failure-562/
2015-07-16 14:52:37 DEBUG    connection _start: Start from server, version: 8.0, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2014 GoPivotal, Inc.', u'capabilities': {}, u'cluster_name': u'rabbit@refinery', u'platform': u'Erlang/OTP', u'version': u'3.5.2'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
2015-07-16 14:52:37 DEBUG    connection _open_ok: Open OK! known_hosts []
2015-07-16 14:52:37 DEBUG    channel __init__: using channel_id: 1
2015-07-16 14:52:37 DEBUG    channel _open_ok: Channel open
2015-07-16 14:52:37 DEBUG    channel _do_close: Closed channel #1
1 / 2: Skipped isa_9505_764988.zip as it has been successfully parsed already. UUID 016bcbf4-e590-4d3f-abf9-c769879148b0
2 / 2: Successfully parsed isa_15576_893881.zip into DataSet with UUID cc9d2534-8108-4b1d-9ee7-d05d9387b734
(refinery-platform)vagrant@refinery:/vagrant/refinery$ ./manage.py process_isatab fritz /vagrant/transfer/failure-562/
2015-07-16 14:52:47 DEBUG    connection _start: Start from server, version: 8.0, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2014 GoPivotal, Inc.', u'capabilities': {}, u'cluster_name': u'rabbit@refinery', u'platform': u'Erlang/OTP', u'version': u'3.5.2'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
2015-07-16 14:52:47 DEBUG    connection _open_ok: Open OK! known_hosts []
2015-07-16 14:52:47 DEBUG    channel __init__: using channel_id: 1
2015-07-16 14:52:47 DEBUG    channel _open_ok: Channel open
2015-07-16 14:52:47 DEBUG    channel _do_close: Closed channel #1
1 / 2: Skipped isa_9505_764988.zip as it has been successfully parsed already. UUID 016bcbf4-e590-4d3f-abf9-c769879148b0
2 / 2: Skipped isa_15576_893881.zip as it has been successfully parsed already. UUID cc9d2534-8108-4b1d-9ee7-d05d9387b734
```

**Comment by hackdna** [comment] 2015-07-16 19:40
just reproduced this by re-running twice with a batch of 50 files:
```
(refinery-platform)[scchsph@scc-dev refinery]$ ./manage.py process_isatab admin ~/sccdata/151-200
2015-07-16 15:14:26 DEBUG    connection _start: Start from server, version: 8.0, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
2015-07-16 15:14:26 DEBUG    connection _open_ok: Open OK! known_hosts []
2015-07-16 15:14:26 DEBUG    channel __init__: using channel_id: 1
2015-07-16 15:14:26 DEBUG    channel _open_ok: Channel open
2015-07-16 15:14:26 DEBUG    channel _do_close: Closed channel #1
1 / 50: Skipped isa_13829_883926.zip as it has been successfully parsed already. UUID 49662fa5-c837-47c5-a637-93ef6da06ad4
2 / 50: Skipped isa_13833_845411.zip as it has been successfully parsed already. UUID 3a858514-a91d-4850-88b9-58b3beb739b7
3 / 50: Skipped isa_13841_851635.zip as it has been successfully parsed already. UUID d10ee40d-17fb-45d6-8133-6d54ab5e93e3
4 / 50: Skipped isa_13864_510837.zip as it has been successfully parsed already. UUID d232ca3d-d3e6-43f4-9cf5-6b7ae65a4d13
5 / 50: Skipped isa_13880_668580.zip as it has been successfully parsed already. UUID dff6d61c-98ff-426b-a9af-4d777ea35965
6 / 50: Skipped isa_13915_951622.zip as it has been successfully parsed already. UUID 7681d5d1-0e49-4514-9adc-510df050c68d
7 / 50: Skipped isa_13919_807758.zip as it has been successfully parsed already. UUID 7fd01c85-c2f1-42cf-8293-dcdf20138b91
8 / 50: Skipped isa_14909_619781.zip as it has been successfully parsed already. UUID 9eee955f-4876-4178-a033-85596ae3913a
9 / 50: Skipped isa_14910_796054.zip as it has been successfully parsed already. UUID ebf50342-89e6-4487-b008-da7afc314f66
10 / 50: Skipped isa_13810_864951.zip as it has been successfully parsed already. UUID 29436d8f-3924-4dba-9b44-40e0de972f75
11 / 50: Successfully parsed isa_14911_701739.zip into DataSet with UUID None
12 / 50: Skipped isa_14959_721643.zip as it has been successfully parsed already. UUID 43128a97-f30d-41a0-b0d8-077f5947b6c9
13 / 50: Successfully parsed isa_13880_954189.zip into DataSet with UUID dff6d61c-98ff-426b-a9af-4d777ea35965
14 / 50: Successfully parsed isa_14909_869928.zip into DataSet with UUID 9eee955f-4876-4178-a033-85596ae3913a
15 / 50: Successfully parsed isa_14995_521844.zip into DataSet with UUID 9de08b61-7d11-4293-90f5-a69b0f7548a1
16 / 50: Successfully parsed isa_14995_760247.zip into DataSet with UUID 9de08b61-7d11-4293-90f5-a69b0f7548a1
17 / 50: Skipped isa_15416_638201.zip as it has been successfully parsed already. UUID 0de958b1-10f0-45ac-8cd0-1a53ec7d7e69
18 / 50: Successfully parsed isa_14911_906861.zip into DataSet with UUID None
19 / 50: Successfully parsed isa_15576_819296.zip into DataSet with UUID 6a367997-20a4-4ed0-bbdd-deedaa9f4c61
20 / 50: Skipped isa_15649_543509.zip as it has been successfully parsed already. UUID c6c7fb48-2cc1-4053-82b3-e4c153ede358
21 / 50: Skipped isa_15771_809838.zip as it has been successfully parsed already. UUID da35c0e9-4c89-4d3b-bd8a-ead5077a677b
22 / 50: Skipped isa_15779_747143.zip as it has been successfully parsed already. UUID ea4a9f38-7e52-442f-87b3-62c78aab84a0
23 / 50: Successfully parsed isa_15576_893881.zip into DataSet with UUID 6a367997-20a4-4ed0-bbdd-deedaa9f4c61
24 / 50: Skipped isa_15621_978252.zip as it has been successfully parsed already. UUID e982d8dd-9d1f-4447-9a17-0b620ca4ed9c
25 / 50: Successfully parsed isa_15800_671535.zip into DataSet with UUID 33bc5088-d5fc-4d0c-8b83-44e7b86afc5e
26 / 50: Successfully parsed isa_15800_834651.zip into DataSet with UUID 33bc5088-d5fc-4d0c-8b83-44e7b86afc5e
27 / 50: Skipped isa_15819_631807.zip as it has been successfully parsed already. UUID b6423e55-a850-4c92-9673-e51dc6a6deac
28 / 50: Skipped isa_15826_729858.zip as it has been successfully parsed already. UUID bc85569c-8532-44fd-84d7-3e5a9a1ed18f
29 / 50: Skipped isa_15849_655437.zip as it has been successfully parsed already. UUID c14cd9be-2e4e-4603-b456-e428516e4cfc
30 / 50: Skipped isa_15880_841516.zip as it has been successfully parsed already. UUID 7f12c302-1f3a-4807-a76a-8a83947418e0
31 / 50: Skipped isa_15890_926926.zip as it has been successfully parsed already. UUID 503b37a8-d267-4f22-8573-6eded89da395
32 / 50: Skipped isa_15918_645078.zip as it has been successfully parsed already. UUID 6c5de4d9-8293-40e4-8247-125ae98971f9
33 / 50: Skipped isa_15981_612050.zip as it has been successfully parsed already. UUID 30335a7c-c496-47f8-b649-3fb684a07ff6
34 / 50: Skipped isa_15982_898524.zip as it has been successfully parsed already. UUID d16bc618-cfcc-4d16-a0a2-e927faac8f67
35 / 50: Skipped isa_15994_917292.zip as it has been successfully parsed already. UUID cd77aabe-c4d3-474b-9cca-6efdbd282c8c
36 / 50: Skipped isa_16012_994452.zip as it has been successfully parsed already. UUID c4b178fd-0d1d-48a4-b3f0-6544c40566d8
37 / 50: Skipped isa_16023_846696.zip as it has been successfully parsed already. UUID 94c5d27d-70ea-4dd6-beec-e11500737c43
38 / 50: Skipped isa_16032_941305.zip as it has been successfully parsed already. UUID 4a19b292-1fb9-457c-a7ae-f06dc78ce63c
39 / 50: Successfully parsed isa_16061_600320.zip into DataSet with UUID 3ac93890-89cb-42c4-ba19-e500ff79e8ef
40 / 50: Successfully parsed isa_16061_917105.zip into DataSet with UUID 3ac93890-89cb-42c4-ba19-e500ff79e8ef
41 / 50: Successfully parsed isa_16100_572948.zip into DataSet with UUID 0a2e6f93-a2af-4022-93aa-b23bfacc2076
42 / 50: Successfully parsed isa_16100_853304.zip into DataSet with UUID 0a2e6f93-a2af-4022-93aa-b23bfacc2076
43 / 50: Skipped isa_16114_676360.zip as it has been successfully parsed already. UUID 1ebb5c73-f304-4af1-b130-bc7731bd4f15
44 / 50: Skipped isa_16131_688596.zip as it has been successfully parsed already. UUID ab90bb44-3992-4407-a99c-15ea1473709e
45 / 50: Skipped isa_16146_519945.zip as it has been successfully parsed already. UUID 430437d4-509c-47d7-94c4-8b6a4f79550d
46 / 50: Successfully parsed isa_16146_677607.zip into DataSet with UUID None
47 / 50: Successfully parsed isa_16165_696431.zip into DataSet with UUID d6323805-cc85-448b-815e-82482708bb95
48 / 50: Successfully parsed isa_15416_821364.zip into DataSet with UUID 0de958b1-10f0-45ac-8cd0-1a53ec7d7e69
49 / 50: Successfully parsed isa_14910_805039.zip into DataSet with UUID ebf50342-89e6-4487-b008-da7afc314f66
50 / 50: Successfully parsed isa_15416_720949.zip into DataSet with UUID 0de958b1-10f0-45ac-8cd0-1a53ec7d7e69
(refinery-platform)[scchsph@scc-dev refinery]$ ./manage.py process_isatab admin ~/sccdata/151-200
2015-07-16 15:26:17 DEBUG    connection _start: Start from server, version: 8.0, properties: {u'information': u'Licensed under the MPL.  See http://www.rabbitmq.com/', u'product': u'RabbitMQ', u'copyright': u'Copyright (C) 2007-2013 GoPivotal, Inc.', u'capabilities': {}, u'platform': u'Erlang/OTP', u'version': u'3.1.5'}, mechanisms: [u'PLAIN', u'AMQPLAIN'], locales: [u'en_US']
2015-07-16 15:26:17 DEBUG    connection _open_ok: Open OK! known_hosts []
2015-07-16 15:26:17 DEBUG    channel __init__: using channel_id: 1
2015-07-16 15:26:17 DEBUG    channel _open_ok: Channel open
2015-07-16 15:26:17 DEBUG    channel _do_close: Closed channel #1
1 / 50: Skipped isa_13829_883926.zip as it has been successfully parsed already. UUID 49662fa5-c837-47c5-a637-93ef6da06ad4
2 / 50: Skipped isa_13833_845411.zip as it has been successfully parsed already. UUID 3a858514-a91d-4850-88b9-58b3beb739b7
3 / 50: Skipped isa_13841_851635.zip as it has been successfully parsed already. UUID d10ee40d-17fb-45d6-8133-6d54ab5e93e3
4 / 50: Skipped isa_13864_510837.zip as it has been successfully parsed already. UUID d232ca3d-d3e6-43f4-9cf5-6b7ae65a4d13
5 / 50: Skipped isa_13880_954189.zip as it has been successfully parsed already. UUID dff6d61c-98ff-426b-a9af-4d777ea35965
6 / 50: Skipped isa_13915_951622.zip as it has been successfully parsed already. UUID 7681d5d1-0e49-4514-9adc-510df050c68d
7 / 50: Skipped isa_13919_807758.zip as it has been successfully parsed already. UUID 7fd01c85-c2f1-42cf-8293-dcdf20138b91
8 / 50: Skipped isa_14909_869928.zip as it has been successfully parsed already. UUID 9eee955f-4876-4178-a033-85596ae3913a
9 / 50: Skipped isa_14910_805039.zip as it has been successfully parsed already. UUID ebf50342-89e6-4487-b008-da7afc314f66
10 / 50: Skipped isa_13810_864951.zip as it has been successfully parsed already. UUID 29436d8f-3924-4dba-9b44-40e0de972f75
11 / 50: Successfully parsed isa_13880_668580.zip into DataSet with UUID dff6d61c-98ff-426b-a9af-4d777ea35965
12 / 50: Successfully parsed isa_14909_619781.zip into DataSet with UUID 9eee955f-4876-4178-a033-85596ae3913a
13 / 50: Successfully parsed isa_14910_796054.zip into DataSet with UUID ebf50342-89e6-4487-b008-da7afc314f66
14 / 50: Successfully parsed isa_14911_701739.zip into DataSet with UUID None
15 / 50: Skipped isa_14959_721643.zip as it has been successfully parsed already. UUID 43128a97-f30d-41a0-b0d8-077f5947b6c9
16 / 50: Successfully parsed isa_14995_521844.zip into DataSet with UUID 9de08b61-7d11-4293-90f5-a69b0f7548a1
17 / 50: Successfully parsed isa_14995_760247.zip into DataSet with UUID 9de08b61-7d11-4293-90f5-a69b0f7548a1
18 / 50: Skipped isa_15416_720949.zip as it has been successfully parsed already. UUID 0de958b1-10f0-45ac-8cd0-1a53ec7d7e69
19 / 50: Successfully parsed isa_15576_819296.zip into DataSet with UUID 6a367997-20a4-4ed0-bbdd-deedaa9f4c61
20 / 50: Skipped isa_15771_809838.zip as it has been successfully parsed already. UUID da35c0e9-4c89-4d3b-bd8a-ead5077a677b
21 / 50: Skipped isa_15779_747143.zip as it has been successfully parsed already. UUID ea4a9f38-7e52-442f-87b3-62c78aab84a0
22 / 50: Successfully parsed isa_15576_893881.zip into DataSet with UUID 6a367997-20a4-4ed0-bbdd-deedaa9f4c61
23 / 50: Skipped isa_15621_978252.zip as it has been successfully parsed already. UUID e982d8dd-9d1f-4447-9a17-0b620ca4ed9c
24 / 50: Skipped isa_15649_543509.zip as it has been successfully parsed already. UUID c6c7fb48-2cc1-4053-82b3-e4c153ede358
25 / 50: Successfully parsed isa_15800_671535.zip into DataSet with UUID 33bc5088-d5fc-4d0c-8b83-44e7b86afc5e
26 / 50: Successfully parsed isa_15800_834651.zip into DataSet with UUID 33bc5088-d5fc-4d0c-8b83-44e7b86afc5e
27 / 50: Skipped isa_15819_631807.zip as it has been successfully parsed already. UUID b6423e55-a850-4c92-9673-e51dc6a6deac
28 / 50: Skipped isa_15826_729858.zip as it has been successfully parsed already. UUID bc85569c-8532-44fd-84d7-3e5a9a1ed18f
29 / 50: Skipped isa_15849_655437.zip as it has been successfully parsed already. UUID c14cd9be-2e4e-4603-b456-e428516e4cfc
30 / 50: Skipped isa_15880_841516.zip as it has been successfully parsed already. UUID 7f12c302-1f3a-4807-a76a-8a83947418e0
31 / 50: Skipped isa_15890_926926.zip as it has been successfully parsed already. UUID 503b37a8-d267-4f22-8573-6eded89da395
32 / 50: Skipped isa_15918_645078.zip as it has been successfully parsed already. UUID 6c5de4d9-8293-40e4-8247-125ae98971f9
33 / 50: Skipped isa_15981_612050.zip as it has been successfully parsed already. UUID 30335a7c-c496-47f8-b649-3fb684a07ff6
34 / 50: Skipped isa_15982_898524.zip as it has been successfully parsed already. UUID d16bc618-cfcc-4d16-a0a2-e927faac8f67
35 / 50: Skipped isa_15994_917292.zip as it has been successfully parsed already. UUID cd77aabe-c4d3-474b-9cca-6efdbd282c8c
36 / 50: Skipped isa_16023_846696.zip as it has been successfully parsed already. UUID 94c5d27d-70ea-4dd6-beec-e11500737c43
37 / 50: Skipped isa_16032_941305.zip as it has been successfully parsed already. UUID 4a19b292-1fb9-457c-a7ae-f06dc78ce63c
38 / 50: Skipped isa_16012_994452.zip as it has been successfully parsed already. UUID c4b178fd-0d1d-48a4-b3f0-6544c40566d8
39 / 50: Successfully parsed isa_16061_600320.zip into DataSet with UUID 3ac93890-89cb-42c4-ba19-e500ff79e8ef
40 / 50: Successfully parsed isa_16061_917105.zip into DataSet with UUID 3ac93890-89cb-42c4-ba19-e500ff79e8ef
41 / 50: Successfully parsed isa_16100_572948.zip into DataSet with UUID 0a2e6f93-a2af-4022-93aa-b23bfacc2076
42 / 50: Successfully parsed isa_16100_853304.zip into DataSet with UUID 0a2e6f93-a2af-4022-93aa-b23bfacc2076
43 / 50: Skipped isa_16114_676360.zip as it has been successfully parsed already. UUID 1ebb5c73-f304-4af1-b130-bc7731bd4f15
44 / 50: Skipped isa_16131_688596.zip as it has been successfully parsed already. UUID ab90bb44-3992-4407-a99c-15ea1473709e
45 / 50: Skipped isa_16146_519945.zip as it has been successfully parsed already. UUID 430437d4-509c-47d7-94c4-8b6a4f79550d
46 / 50: Successfully parsed isa_16146_677607.zip into DataSet with UUID None
47 / 50: Skipped isa_16165_696431.zip as it has been successfully parsed already. UUID d6323805-cc85-448b-815e-82482708bb95
48 / 50: Successfully parsed isa_14911_906861.zip into DataSet with UUID None
49 / 50: Successfully parsed isa_15416_821364.zip into DataSet with UUID 0de958b1-10f0-45ac-8cd0-1a53ec7d7e69
50 / 50: Successfully parsed isa_15416_638201.zip into DataSet with UUID 0de958b1-10f0-45ac-8cd0-1a53ec7d7e69
```

**Comment by ngehlenborg** [comment] 2015-07-17 03:54
I am also unable to reproduce this.

**Comment by hackdna** [comment] 2015-07-17 14:25
Have you tried with a batch of 50 files?

**Comment by flekschas** [comment] 2015-07-17 14:52
Yes works as expected.

**Comment by ngehlenborg** [comment] 2015-07-21 13:23
@hackdna: Still no luck?

**Comment by hackdna** [comment] 2015-07-21 13:37
Were there any fixes pushed?

**Comment by flekschas** [comment] 2015-07-21 13:43
You are the only one reporting that error. Since I can't reproduce it I am unable to to debug.

**Comment by hackdna** [comment] 2015-07-21 18:01
It shows one version.

**Comment by ngehlenborg** [comment] 2015-07-21 18:06
Version 1?

**Comment by hackdna** [comment] 2015-07-21 18:08
Yes

**Comment by ngehlenborg** [comment] 2015-07-22 13:03
Ok, so it is importing those data sets multiple times.

**Comment by ngehlenborg** [comment] 2015-07-22 13:04
I'm moving this to [0.0.5](https://github.com/parklab/refinery-platform/milestones/Release%200.0.5)

**Comment by flekschas** [comment] 2015-11-09 15:00
I've uploaded `isa_9505_764988.zip` twice on https://refinery-dev.stemcellcommons.org through the UI and could not reproduce the issue described. Also, I've tested it locally with the same file and another file using the batch import command and could not reproduce the error either.

**Closed by flekschas** 2015-11-09 15:00 UTC
Labels: bug, import, metadata
