### ISSUE TITLE
Unhandled UnicodeEncodeError in visualization_manager

### ISSUE THREAD

**Issue by hackdna** [parklab/refinery-platform#1254] opened 2016-07-18 21:53 UTC
Commit: ec43d5ba6d2f6cd5efcd583c9f420c11a4d5f548

### Steps to reproduce
Unknown, log received by email.

### Observed behavior
The following error is logged:
```
Traceback (most recent call last):

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/srv/refinery-platform/refinery/core/views.py", line 717, in solr_igv
    session_urls = igv_multi_species(solr_results, solr_annot)

  File "/srv/refinery-platform/refinery/visualization_manager/views.py", line 184, in igv_multi_species
    sample_file = addIGVSamples(fields, unique_species[k]['solr'])

  File "/srv/refinery-platform/refinery/visualization_manager/views.py", line 441, in addIGVSamples
    tempsampname.write(pheno_results)

UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b1' in position 137: ordinal not in range(128)
```
Additional info:
```
'PATH_INFO': u'/solr/igv/'
'HTTP_REFERER': 'https://beta.stemcellcommons.org/data_sets/340087ff-90fe-445b-82a1-04b6772e25b1/'
```

### Expected behavior
Error should be handled appropriately.

**Comment by scottx611x** [comment] 2016-07-19 14:06
Related to #1251

**Comment by scottx611x** [comment] 2016-07-22 13:21
I believe this issue is addressed by adding the following code:

``` python
try:
    temp_sample_name.write(pheno_results)
except UnicodeDecodeError:
    temp_sample_name.write(pheno_results.encode("utf-8"))
```

but since theres is no clear way to reproduce this issue, I'm not sure how to move forward...

**Comment by scottx611x** [comment] 2016-07-22 14:06
@hackdna Let me know your thoughts here, I feel like adding the Error handling proposed above _should_ be sufficient

**Comment by hackdna** [comment] 2016-07-22 19:14
Thanks, I think that's probably fine though we should add a warning message from UnicodeEncodeError exception to the log.

**Comment by scottx611x** [comment] 2016-07-22 19:19
Closing as of commit: 6f7d934ee10d08d0bb9ff405e16f63e8c4cafdcc

**Closed by scottx611x** 2016-07-22 19:19 UTC
Labels: bug, server, solr, visualization
